name: Auto Scrape Holiday Data

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch: 

# TAMBAHKAN INI: Memberi izin robot untuk menulis ke repo
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Update ke v4 (lebih stabil)

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Update ke v4
        with:
          node-version: '20' # Gunakan Node 20 (LTS terbaru)

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Run Scraper
        run: node scraper.js

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add holidays.json
          # Commit hanya jika ada perubahan agar tidak error
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated update: $(date)" && git push)
